trigger:
- main

pool:
  vmImage: ubuntu-latest

stages:
- stage: Validate
  displayName: Validate
  jobs:
  - job: Validate
    steps:
    - checkout: self
    - script: echo Hello, world!
      displayName: 'One-liner Script'
    - script: echo 'This is the file' > myfile.txt
      displayName: 'Run something'

  # - job: ActivityonWindowsVM
  #   pool:
  #   name: Default
  #     - task: PowerShell@2
  #    inputs:
  #      targetType: 'inline'
  #      script: |
  #        # Write your PowerShell commands here.
         
  #        Write-Host "Hello World"

# - stage: Build
#      - task: VSBuild@1
#       inputs:
#         solution: '$(solution)'
#         msbuildArgs: '/p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:PackageLocation="$(build.artifactStagingDirectory)"'
#         platform: '$(buildPlatform)'
#         configuration: '$(buildConfiguration)'

    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'drop'
        publishLocation: 'Container'

 - stage: Release
   displayName: Releasing
   jobs:
   - job:
   - deployment:
     displayName: Releasing to VM
     environment: 
         name: test
         resourceType: VirtualMachine
         resourceName: azurepoc
     strategy:
       runOnce:
         deploy:
           steps:
           - task: CopyFiles@2
             inputs:  
               SourceFolder: '$(Agent.WorkFolder)\1\drop'
               Contents: '**\*.zip'
               OverWrite: true
              TargetFolder: '/home/azurepoc/' 
